
run_simple:
	@python3 ./simple_imp.py < ${input} > ${output}
run_go:
	@go run ./unit_phone_number.go < ${input} > ${output}
run_go_3:
	@go run ./unit_phone_number.go 3 < ${input} > ${output}
run_go_n:
	@go run ./unit_phone_number.go ${n} < ${input} > ${output}
run_test:
	@go test -v
